# Generated by Django 4.2 on 2023-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('short_id', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='short id')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
                ('body', models.CharField(blank=True, max_length=10000, verbose_name='body')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
                ('short_id', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='short id')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('title_fa', models.CharField(max_length=1000, verbose_name='Persian title')),
                ('title_en', models.CharField(max_length=1000, verbose_name='English title')),
                ('summary', models.CharField(blank=True, max_length=10000, verbose_name='summary')),
                ('published_at', models.DateTimeField(verbose_name='published at')),
                ('release_year', models.SmallIntegerField(null=True, verbose_name='release year')),
                ('rate_percentage', models.FloatField(null=True, verbose_name='rate percentage')),
                ('imdb_rank_percent', models.FloatField(null=True, verbose_name='IMDb rank percent')),
                ('duration', models.CharField(blank=True, max_length=10, verbose_name='duration')),
                ('visits', models.IntegerField(null=True, verbose_name='visits')),
                ('cover_image', models.ImageField(null=True, upload_to='', verbose_name='cover image')),
                ('poster_image', models.ImageField(null=True, upload_to='', verbose_name='poster image')),
                ('genres', models.ManyToManyField(related_name='movies', to='core.genre', verbose_name='genres')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'db_table': 'Movie',
                'ordering': ['-published_at'],
            },
        ),
    ]
